import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';

function ChangeLogPage() {
    return (
        <Container className="mt-5">
            <Row>
                <Col>
                    <h3>ChangeLog - Versions refer to Azure Deployments</h3>
                    <ul>
                        <li>
                            <h5>Version 0_1 (Initial Release)</h5>
                            <ul>
                                <li><strong>Implemented basic functionality for the MERN web app.</strong></li>
                                <li>Single page with data entry and previous data display</li>
                                <li>Previous data display has simple delete button</li>
                                <li>Only API GET call is /ips/all which displays all records</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_2</h5>
                            <ul>
                                <li><strong>Improved data presentation, delete confirm and IPS API additions</strong></li>
                                <li>Data presented in compact form with expand mechanism</li>
                                <li>Delete button now has confirmation prompt - to avoid accidental deletion</li>
                                <li>Added API GET calls for /ips/:id (IPS Bundle - JSON) and /ipsraw/:id (MongoDb Native format - JSON)</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_3</h5>
                            <ul>
                                <li><strong>Implemented QR Generator, (non-functional) Data Upload page and Navigation.</strong></li>
                                <li>QR code Generation of IPS Bundle and MongoDb record format.</li>
                                <li>Data Upload page just a stub for later development</li>
                                <li>Navigation Bar added for easy access to all pages</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_4</h5>
                            <ul>
                                <li><strong>Per-record QR Button, new data format for both API and QR Generator</strong></li>
                                <li>QR Button added to previous record display to jump to QR Generator Page for that record</li>
                                <li>Minimised IPS data format - Plain Text. Same format as generated by SmartDoc (DMICP) and read by FUB-QR (SmartPhone App)</li>
                                <li>QR Generator now uses the new format as additional option -checked is indeed readable by FUB-QR</li>
                                <li>API GET call for minimised format is /ipsbasic/:id</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_5</h5>
                            <ul>
                                <li><strong>Better Navigation format and QR URL for Patient</strong></li>
                                <li>QR Generator includes new mode representing - in Plain Text - the API endpoint for the IPS Bundle</li>
                                <li>Concept would be to download QR image and give/send patient</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_6</h5>
                            <ul>
                                <li><strong>Added About IPS and ChangeLog page, Hide data entry form</strong></li>
                                <li>About IPS page to give brief context - non-sensitive</li>
                                <li>ChangeLog page to track project updates and improvements.</li>
                                <li>Hide data entry form button to allow more space for data display</li>
                                <li>Added additional data validation before submission</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_7</h5>
                            <ul>
                                <li><strong>Added real functionality to Bulk Upload page</strong></li>
                                <li>Bulk Upload page to allow pasting of multiple records for conversion</li>
                                <li>Format expected is that generated by accompanying DMICP SmartDoc</li>
                                <li>Main fields are comma separated, medication and allergies are then semicolon separated</li>
                                <li>Validation of data and confirmation before submission</li>
                                <li>Process allows valid records to be submitted whilst skipping invalid ones</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_8</h5>
                            <ul>
                                <li><strong>Added UUID validator for Bulk Upload</strong></li>
                                <li>UUID validator is basic regex - so not true validator - but will suffice for now</li>
                                <li>SmartDoc will generate valid UUIDs by default, so validator just to avoid incorrect manual efforts</li>
                                <li>Separate message if no supplied records pass validation</li>
                            </ul>
                        </li>
                    </ul>
                </Col>
            </Row>
        </Container>
    );
}

export default ChangeLogPage;
