import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';

function ChangeLogPage() {
    return (
        <Container className="mt-5">
            <Row>
                <Col>
                    <h3>ChangeLog - Versions refer to Cloud Deployments</h3>
                    <ul>
                        <li>
                            <h5>Version 0_1 (Initial Release) - 2nd May 2024</h5>
                            <ul>
                                <li><strong>Implemented basic functionality for the MERN web app.</strong></li>
                                <li>Single page with data entry and previous data display</li>
                                <li>Previous data display has simple delete button</li>
                                <li>Only API GET call is /ips/all which displays all records</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_2 - 3rd May 2024</h5>
                            <ul>
                                <li><strong>Improved data presentation, delete confirm and IPS API additions</strong></li>
                                <li>Data presented in compact form with expand mechanism</li>
                                <li>Delete button now has confirmation prompt - to avoid accidental deletion</li>
                                <li>Added API GET calls for /ips/:id (IPS Bundle - JSON) and /ipsraw/:id (MongoDb Native format - JSON)</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_3 - 4th May 2024</h5>
                            <ul>
                                <li><strong>Implemented QR Generator, (non-functional) Data Upload page and Navigation.</strong></li>
                                <li>QR code Generation of IPS Bundle and MongoDb record format.</li>
                                <li>Data Upload page just a stub for later development</li>
                                <li>Navigation Bar added for easy access to all pages</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_4 - 4th May 2024</h5>
                            <ul>
                                <li><strong>Per-record QR Button, new data format for both API and QR Generator</strong></li>
                                <li>QR Button added to previous record display to jump to QR Generator Page for that record</li>
                                <li>Minimised IPS data format - Plain Text. Same format as generated by SmartDoc (DMICP) and read by FUB-QR (SmartPhone App)</li>
                                <li>QR Generator now uses the new format as additional option -checked is indeed readable by FUB-QR</li>
                                <li>API GET call for minimised format is /ipsbasic/:id</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_5 - 4th May 2024</h5>
                            <ul>
                                <li><strong>Better Navigation format and QR URL for Patient</strong></li>
                                <li>QR Generator includes new mode representing - in Plain Text - the API endpoint for the IPS Bundle</li>
                                <li>Concept would be to download QR image and give/send patient</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_6 - 5th May 2024</h5>
                            <ul>
                                <li><strong>Added About IPS and ChangeLog page, Hide data entry form</strong></li>
                                <li>About IPS page to give brief context - non-sensitive</li>
                                <li>ChangeLog page to track project updates and improvements.</li>
                                <li>Hide data entry form button to allow more space for data display</li>
                                <li>Added additional data validation before submission</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_7 - 6th May 2024</h5>
                            <ul>
                                <li><strong>Added real functionality to Bulk Upload page</strong></li>
                                <li>Bulk Upload page to allow pasting of multiple records for conversion</li>
                                <li>Format expected is that generated by accompanying DMICP SmartDoc</li>
                                <li>Main fields are comma separated, medication and allergies are then semicolon separated</li>
                                <li>Validation of data and confirmation before submission</li>
                                <li>Process allows valid records to be submitted whilst skipping invalid ones</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_8 - 6th May 2024</h5>
                            <ul>
                                <li><strong>Added UUID validator for Bulk Upload</strong></li>
                                <li>UUID validator is basic regex - so not true validator - but will suffice for now</li>
                                <li>SmartDoc will generate valid UUIDs by default, so validator just to avoid incorrect manual efforts</li>
                                <li>Separate message if no supplied records pass validation</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_9 - 6th May 2024</h5>
                            <ul>
                                <li><strong>Logo and Navbar Changes</strong></li>
                                <li>Added new logo to replace stock React App one</li>
                                <li>Navbar is now fixed at top</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_10 - 8th May 2024</h5>
                            <ul>
                                <li><strong>QR Code Size Check</strong></li>
                                <li>QR Code data size check - and user feedback - to avoid display errors</li>
                                <li>Threshold set to 3000 but most codes at this size unreadable except on most recent SmartPhones</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_11 - 9th May 2024</h5>
                            <ul>
                                <li><strong>New XML Format and IPS JSON Format change</strong></li>
                                <li>IPS Bundle format now compatible with the <a href="https://ipsviewer.com" target="_blank" rel="noopener noreferrer">IPS Viewer</a></li>
                                <li>This is closer to the IPS.net <a href="https://github.com/jddamore/IPSviewer/tree/main/samples" target="_blank" rel="noopener noreferrer">samples and examples</a></li>
                                <li>In particular it leads with a Composition resource</li>
                                <li>XML format added to API - modelled on JSON format</li>
                                <li>API GET is /ipsxml/:id</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_12 - 9th May 2024</h5>
                            <ul>
                                <li><strong>Added API GET Data Viewer</strong></li>
                                <li>Allows more convient viewing of data formats returned by the various API GET endpoints</li>
                                <li>API Button added to individual records on HomePage as quick link</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_13 - 10th May 2024</h5>
                            <ul>
                                <li><strong>Legacy IPS JSON and Screen Realestate</strong></li>
                                <li>Added IPS Legacy format to API endpoints and API Page - based on version 2 of bundle</li>
                                <li>For illustration purposes only - as comparison to 'regular' version.</li>
                                <li>API GET is /ipslegacy/:id</li>
                                <li>Various Screen realestate improvements for QR and API pages</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_14 - 11th May 2024</h5>
                            <ul>
                                <li><strong>Cosmetic changes and hyperlinks</strong></li>
                                <li>Links in various places to aide testing</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_15 - 17th May 2024</h5>
                            <ul>
                                <li><strong>Added API GET and POST</strong></li>
                                <li>API GET allows the return of an IPS Bundle using the endpoint /ipsbyname/:name/:given</li>
                                <li>API POST allows the creation of a new entry in the database from an IPS JSON Bundle</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_16 - 18th May 2024</h5>
                            <ul>
                                <li><strong>Added Gender and Conditions</strong></li>
                                <li>Large update as entire schema changed</li>
                                <li>All input, import, export and generation code changed</li>
                                <li>Old entries against previous schema no longer valid as two fields have changed name</li>
                                <li>nationality to nation, and severity to criticality</li>
                                <li>Old database will be deleted</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_17 - 19th May 2024</h5>
                            <ul>
                                <li><strong>Replaced 'Display All' with Search Functionality</strong></li>
                                <li>Search for IPS records based on patient's name</li>
                                <li>API GET call is /ips/search/:name</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_18 - 19th May 2024</h5>
                            <ul>
                                <li><strong>Patient Selection Preservation</strong></li>
                                <li>Selected patients are preserved across the App</li>
                                <li>At least one patient needs to be selected to display anything on QR and API pages</li>
                                <li>'Select Records' dropdown is now confined to only those records returned by search</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_19 - 19th May 2024</h5>
                            <ul>
                                <li><strong>Optional :id endpoints</strong></li>
                                <li>API GET endpoints that use /:id will now accept both MongoDB internal _id and IPS id (packageUUID)</li>
                                <li>Improvements to 'Active' Patient functionality throughout app</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_20 - 22nd May 2024</h5>
                            <ul>
                                <li><strong>Added VitalsIQ API Page</strong></li>
                                <li>Page to allow direct access to the VitalsIQ API</li>
                                <li>API is at https://4202xiwc.offroadapps.dev:62444/Fhir/ips/json/surname/firstname</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_21 - 23rd May 2024</h5>
                            <ul>
                                <li><strong>API Comms Client-to-Server</strong></li>
                                <li>Axios GET code moved to server-side to avoid BPS issues</li>
                                <li>API GET used internally - but could be used extenally - is /fetchipsora/surname/firstname</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_22- 23rd May 2024</h5>
                            <ul>
                                <li><strong>Record Creation from ORA IPS Bundle</strong></li>
                                <li>Can now convert an VitalsIQ IPS Bundle to a MongoDb Record</li>
                                <li>Made the Condition Date optional - defaults to today's date - to facilate testing</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_23- 23rd May 2024</h5>
                            <ul>
                                <li><strong>Added API POST to ORA</strong></li>
                                <li>API POST allows the sending IPS JSON Bundle to VitalsIQ WebApp</li>
                                <li>Internal API endpoint is /pushipsora</li>
                                <li>External API endpoint is at https://4202xiwc.offroadapps.dev:62444/Fhir/ips/json</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_24 - 26th May 2024</h5>
                            <ul>
                                <li><strong>Added API GET for BEER</strong></li>
                                <li>API GET allows the return of an IPS Bundle with the BEER data format using the endpoint /ipsbeer/:id</li>
                                <li>Note: At this point BEER format is under development - so this represents an initial attempt</li>
                                <li>API and QR Page include BEER modes</li>
                                <li>QR Page displays the QR size in bites</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_25 - 27th May 2024</h5>
                            <ul>
                                <li><strong>Added BEER Garden Page</strong></li>
                                <li>Page to allow conversion between MongoDb and BEER formats</li>
                                <li>BEER format is under development - so this represents an initial attempt</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_26 - 27th May 2024</h5>
                            <ul>
                                <li><strong>Added NavBar Search</strong></li>
                                <li>Search for IPS records based on patient's family/surname</li>
                                <li>Removed HomePage from NavBar - as same functionality available from clicking on IPS Main Title and Logo</li>
                                <li>Creates more space for other NavBar items</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_27 - 28th May 2024</h5>
                            <ul>
                                <li><strong>Added Edit Functionality</strong></li>
                                <li>Allows editing of existing IPS records</li>
                                <li>Added Edit button to individual records on HomePage</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_28 - 29th May 2024</h5>
                            <ul>
                                <li><strong>Added Spinner</strong></li>
                                <li>Added Spinner to indicate loading for asynchronous functions</li>
                                <li>Spinner appears for any action that relies on fetching or posting data</li>
                                <li>Whether using the internal or external API</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_29 - 30th May 2024</h5>
                            <ul>
                                <li><strong>Added Observation Resource</strong></li>
                                <li>Added Observation resource to IPS Bundle</li>
                                <li>Observation resource includes a code, value, and date</li>
                                <li>If value start numerical then valueQuantity, if just text then bodySite, if blank then simple ob e.g. symptom</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_30 - 1st Jun 2024</h5>
                            <ul>
                                <li><strong>Added TimeStamp</strong></li>
                                <li>Added fixed TimeStamp - previously generated with IPS bundle</li>
                                <li>Closer to IPS concept and aides BEER format development - items can be added post-timestamp</li>
                                <li>Generated whether by manual addition or Data Upload.</li>
                                <li>If API GET used then the TimeStamp is the that provided by the IPS JSON bundle fetched</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_31 - 1st Jun 2024</h5>
                            <ul>
                                <li><strong>Added Observation and Allergy Dropdowns</strong></li>
                                <li>Observation dropdown for key vital signs - temperature, blood pressure, pulse, respiration etc</li>
                                <li>Allergy dropdown for criticality - low, medium, high</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_32 - 3rd Jun 2024</h5>
                            <ul>
                                <li><strong>Further BEER Format Development</strong></li>
                                <li>Medication and Observations formatted differently depending on whether past or future relative to timestamp</li>
                                <li>Vital Sign observations in particular have a highly compact form</li>
                                <li>Design varies slightly from earlier concept but basic ideas remain</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_33 - 6th June 2024</h5>
                            <ul>
                                <li><strong>Added BEER - IPS JSON Conversion in BEER Garden</strong></li>
                                <li>Manually edited BEER data can be converted to IPS JSON format or Native MongoDB</li>
                                <li>IPS JSON (converted internally from MongoDb) or manually edited - can be converted to BEER format</li>
                                <li>Byte size displayed for both formats</li>
                                <li>Neither option affects the stored record - just for display purposes</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_34 - 9th June 2024</h5>
                            <ul>
                                <li><strong>Added New Update/Edit Endpoint</strong></li>
                                <li>Added new endpoint to allow updating of existing IPS records using UUID</li>
                                <li>API PUT call is /ipsuuid/:id</li>
                                <li>This means an external system that has POST/created a record - perhaps before patient id known - can then update it later</li>
                                <li>Changes to unique Patient data - e.g. name - are treated as edits, Medication, Allergies, Conditions and Observations are added to the record</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_3 - 12th June 2024</h5>
                            <ul>
                                <li><strong>Added API Documentation Page</strong></li>
                                <li>Page to allow easy access to all API endpoints and their descriptions</li>
                                <li>API Documentation Page is accessible from the NavBar</li>
                                <li>/ipsbyname is now case-insensitive</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_36 - 12th June 2024</h5>
                            <ul>
                                <li><strong>Organization added</strong></li>
                                <li>Organization field added to MongoDB record</li>
                                <li>Previously was not being read and was being automatically set in exports/conversions to 'UK DMS'</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_37 - 13th June 2024</h5>
                            <ul>
                                <li><strong>Added API POST to NLD</strong></li>
                                <li>API POST allows the sending IPS JSON Bundle to NLD WebApp</li>
                                <li>Internal API endpoint is /pushipsnld</li>
                                <li>External API endpoint is at https://medicalcloud.orange-synapse.nl/api/fhir/1</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_38 - 13th June 2024</h5>
                            <ul>
                                <li><strong>IPS BEER Parsing Delimiter Improvements</strong></li>
                                <li>IPS BEER format can use various delimiters - newline, semicolon, pipe, colon, and @</li>
                                <li>If no delimiter is specified then all are tried before failing</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_39 - 14th June 2024</h5>
                            <ul>
                                <li><strong>Added CDA Functionality</strong></li>
                                <li>API POST to create MongoDb record from CDA XML - endpoint is /ipsfromcda</li>
                                <li>API POST to convert CDA XML to IPS JSON Bundle - endpoint is /convertcdatoips - service only, no record is created</li>
                                <li>API POST to convert CDS XML to BEER format - endpoint is /convertcdatobeer - service only, no record is created</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_40 - 15th June 2024</h5>
                            <ul>
                                <li><strong>Added API Calls for IPS HL7 v2.8</strong></li>
                                <li>API GET allows the return of an IPS Bundle with the HL7 v2.8 data format using the endpoint /ipshl728/:id</li>
                                <li>API POST allows conversion of MongoDb record to HL7 v2.8 format - endpoint is /convertmongo2hl7</li>
                                <li>Further endpoints for HL7 v2.8 are planned - note: there are likely formatting errors in the current implementation</li>
                                <li>The idea is give an approximate HL7 v2.8 format - not a perfect one - to judge likely file size and content</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_41 - 7th Aug 2024</h5>
                            <ul>
                                <li><strong>Australian IPS Format</strong></li>
                                <li>Ability to successfully POST /ipsbundle from IPS JSON Bundle generated by Australian Team</li>
                                <li>Note, interesting use of Medication resource embedded in MedicationRequest resource</li>
                                <li>Format passes IPSViewer checks</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_42 - 2nd September 2024</h5>
                            <ul>
                                <li><strong>Added Immunization Resource</strong></li>
                                <li>Integrated Immunization resource into the backend and frontend systems</li>
                                <li>Immunization resource includes a date, name, and system</li>
                                <li>Name can be either a textual entry or a code, with the system indicating the coding system used (e.g., SNOMED, WHO ATC) or a reference url</li>
                                <li>All conversions updated including 'from CDA', 'to HL7 2.8' and 'to and from BEER'</li>
                                <li>Note: HL7 2.8 message validation may show errors due to lack of data, but the data provided is in the correct positions. Please visit <a href="https://www.parsehog.com/hl7/parser" target="_blank" rel="noopener noreferrer">Parsehog HL7 Parser</a> to validate and check the message structure yourself.</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_43 - 3rd September 2024</h5>
                            <ul>
                                <li><strong>Added PDF Generation Feature</strong></li>
                                <li>Implemented a new PDF generation function that allows patient reports to be viewed and downloaded as PDF documents</li>
                                <li>The PDF document is formatted to fit within A4 page dimensions, with automatic text wrapping to ensure readability</li>
                                <li>Patient data, including Medications, Allergies, Conditions, Observations, and Immunizations, are included in the PDF report</li>
                                <li>PDF opens in a new tab with a dynamic filename based on the patient's name, allowing for easy download and identification</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_44 - 13th November 2024</h5>
                            <ul>
                                <li><strong>HL7 2.8 Conversion Functionality</strong></li>
                                <li>Added endpoints for chaining HL7 2.8 to MongoDB, then MongoDB to IPS JSON</li>
                                <li>Extended API documentation with complete list of available endpoints for CRUD operations, conversions, and integrations with external systems</li>
                                <li>API documentation pages updated to reflect latest changes</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_45 - 26th November 2024</h5>
                            <ul>
                                <li><strong>Gzip Compression Support</strong></li>
                                <li>Introduced middleware to handle gzip-encoded requests and responses</li>
                                <li>API now supports gzip encoding for both incoming and outgoing data, optimizing bandwidth usage</li>
                                <li>Enhanced compatibility with external clients by allowing Content-Encoding and Accept-Encoding headers for gzip</li>
                                <li>Added safeguards to bypass compression for internal calls, ensuring seamless frontend-backend communication</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_46 - 28th November 2024</h5>
                            <ul>
                                <li><strong>Encryption Support with AES-256</strong></li>
                                <li>Added middleware to handle AES-256 encrypted requests and responses</li>
                                <li>API now supports encrypted communication via `x-encrypted` and `accept-encryption` headers, ensuring secure data transfer</li>
                                <li>Implemented seamless integration of gzip compression and AES-256 encryption, allowing data to be compressed before encryption</li>
                                <li>Introduced a `/test` endpoint to facilitate testing of combined encryption and compression functionality</li>
                                <li>Enhanced logging and error handling to aid debugging and ensure robustness during data transformations</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_47 - 30th November 2024</h5>
                            <ul>
                                <li><strong>Encryption Support with AES-256 base64</strong></li>
                                <li>Introduced support for Base64-encoded encryption via <code>content-encoding: base64</code> and <code>accept-encoding: base64</code> headers</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_48 - 4th December 2024</h5>
                            <ul>
                                <li><strong>Enhanced ID Handling and Compression/Encryption Preview</strong></li>
                                <li>Implemented logic to seamlessly handle IPS records with non-UUID identifiers</li>
                                <li>All API endpoints now support retrieving records using non-UUID identifiers, resolving issues where such records could not be accessed after creation via API calls using those identifiers</li>
                                <li>New checkbox feature on APi Page allows users to toggle encryption and compression for API responses</li>
                                <li>The existing file size display can then be used for comparisons</li>
                                <li>Likewise, the download feature can then be used for the compressed/encrypted versions</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_49 - 6th Feburary 2025</h5>
                            <ul>
                                <li><strong>Added Unified Schema Changes</strong></li>
                                <li>API GET allows the return of an IPS Bundle with the unified schema using the endpoint /ipsunified/:id</li>
                                <li>Common Code System changes added - system + code - for all clinical resources</li>
                                <li>HL7 2.x is now 2.3 and not 2.8 but only difference is minor change to MSH segment</li>
                                <li>IPS FHiR Bundle to Schema conversion still accepts all variations so far used</li>
                                <li>UI changes made to better accomodate increased number of fields per resource</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_50 - 7th February 2025</h5>
                            <ul>
                                <li><strong>Generic External GET and POST Pages</strong></li>
                                <li>Added target drop-down for external endpoint selection (VitalsIQ, NLD, IPS SERN) and allowed manual endpoint editing</li>
                                <li>Implemented data format selection options: IPS Unified, IPS Prev JSON, and IPS Legacy</li>
                                <li>Introduced a HL7 wrapper toggle to optionally wrap fetched IPS data</li>
                                <li>Modified GET page to dynamically construct API calls based on selected data format and endpoint</li>
                                <li>Updated UI to conditionally render section headers (e.g. Medications, Allergies, Conditions, Observations, Immunizations) only when data is present</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_51 - 12th February 2025</h5>
                            <ul>
                                <li><strong>New HL7 2.x Format with Common Code System (CCS)</strong></li>
                                <li>Added CCS elements to HL7 2.x format - both extraction and creation</li>
                                <li>Note: This will no longer be compatible with previous implementation</li>
                                <li>Added CCS element extraction from CDA XML format</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_52 - 14th February 2025</h5>
                            <ul>
                                <li><strong>FHiR XML to FHiR JSON Conversion Added</strong></li>
                                <li>Developed a specialized conversion function that handles the nuances of FHiR XML (including capitalization, array enforcement, and HTML reassembly) to produce proper IPS JSON. (There is also a more generic version for other uses for not sufficient for FHiR)</li>
                                <li><strong>Expanded IPS Bundle Parser</strong></li>
                                <li>Updated the IPS Bundle parser to accept additional XML formats and variations present in the 'SF' samples (e.g. MedicationAdministration resources used for the medication element).</li>
                                <li><strong>XML Support for IPS Bundle Endpoints</strong></li>
                                <li>Endpoints that previously accepted only FHiR JSON now seamlessly process FHiR XML data without requiring special headers. That includes if the data has first been encrypted and/or compressed.</li>
                                <li><strong>Enhanced /test Endpoint Functionality</strong></li>
                                <li>The /test endpoint now supports decryption/encryption and compression/decompression of XML, returning the raw XML as plain text.</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_53 - 3rd March 2025</h5>
                            <ul>
                                <li><strong>Experimental XMPP Integration</strong></li>
                                <li>
                                    Introduced new endpoints that enable integration with an external XMPP server to send and receive messages.
                                    <br />
                                    <em>Important:</em> This functionality is still experimental and requires:
                                    <ul>
                                        <li>An XMPP server reachable over a <strong>non-encrypted WebSocket</strong> (e.g. <code>ws://</code>).</li>
                                        <li>Proper environment variables set in the <code>.env</code> file or via Azure/OpenShift mechanisms (e.g., <code>XMPP_SERVICE</code>, <code>XMPP_DOMAIN</code>, <code>XMPP_USERNAME</code>, <code>XMPP_PASSWORD</code>, <code>XMPP_ROOM</code>).</li>
                                    </ul>
                                    If these conditions are not met, the XMPP features will not function as intended.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_54 - 18th March 2025</h5>
                            <ul>
                                <li><strong>Updated Encryption System with HMAC</strong></li>
                                <li>Encryption and decryption functions to use a 16-byte (128-bit) HMAC instead of the full 32-byte version for compatibility with joint project requirements.</li>
                                <li>Refactored middleware to validate and process encrypted JSON payloads, ensuring HMAC verification before decryption. Improved error handling and logging for malformed requests.</li>
                                <li>Encryption now includes the truncated HMAC (16 bytes) alongside the IV and ciphertext, ensuring integrity while reducing payload size.</li>
                            </ul>
                        </li>
                        <li>
                            <h5>Version 0_55 - 19th March 2025</h5>
                            <ul>
                                <li><strong>New Raw Binary Format for Encrypted Payloads</strong></li>
                                <li>Introduced support for <code>application/octet-stream</code> requests and responses, featuring a 16-byte IV, 16-byte HMAC, and gzipped data.</li>
                                <li>This allows clients to send and receive encrypted &amp; compressed data more efficiently without JSON overhead, improving performance.</li>
                                <li>Updated documentation to clarify how to use the binary format alongside existing JSON encryption methods.</li>
                            </ul>
                        </li>
                    </ul>
                </Col>
            </Row>
        </Container>
    );
}

export default ChangeLogPage;
