# sushi-config.yaml
canonical: http://example.org/fhir/IPSUnified
fhirVersion: 4.0.1
id: ips-unified
version: 0.1.0
name: IPSUnified
status: draft
releaseLabel: "0.1.0"
copyrightYear: 2025
description: >
  An Implementation Guide for the IPS unified bundle schema.
license: CC0-1.0
