# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mern-webapp-mike

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: mern-webapp-mike         # Your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'              # Path to your project (here, the repository root)
  NODE_VERSION: '14.x'                        # Set your preferred Node.js version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write      # Required for Azure login
      contents: read       # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest

      - name: npm install, build, and test
        env:
          CI: false
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7CCC5B26B7E04A9EBAFB67397E750984 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA90401823C54F7594EE1EC4D926BCC2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_474AE9D647544212BED7DBD188C1CD25 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
